# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://kefirlily.cn
date_format: "ordinal"
title: John He
subtitle: "Stay hungry, stay foolish"  
description: "贺超的个人博客"  
keywords: 贺超, John He, kefirlily, hechao
timezone: Asia/Shanghai 
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: John He
organization: 
organization_url: 
github_username: DreamChao
location: Xi'an, China
email: plhechao@163.com 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: 
    label: Home

  -
    href: categories
    label: Categories

#   -
#     href: /archives/
#     label: 归档

  -
    href: wiki
    label: Wiki

  -
    href: links
    label: Links

  -
    href: aboutme
    label: About me

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: DreamChao/dreamchao.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
#https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: blog-comments
    oauth:
        client_id: c38e262d827deafa32b6
        client_secret: b0215aff68d7ae22b4d771d6acbb2415d8609136
#https://github.com/gitalk/gitalk#install
gitalk:
    owner: DreamChao
    
    repo: blog-comments
    clientID: c38e262d827deafa32b6
    clientSecret: b0215aff68d7ae22b4d771d6acbb2415d8609136
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
